### ISSUE TITLE
Is turn based combat actually fun?

### ISSUE THREAD

**Issue by Dloughrin** [Dloughrin/Project-Kazoo#3]
Wanted to put this on here somewhere. Been trying to decide whether or not the turn based combat I had in mind will be worth using, and if  not, what to replace it with. I think it can be fun, but most of the time I think what I enjoy about it is customizing classes and abilities, not the combat itself.      
        
Any input is appreciated.

**Comment by magyk81** [comment]
Only turn-based combat game I've played is Pokemon. From what I've heard, it gets boring and repetitive especially when grinding. I've heard of a game that tackled this problem. Turn-based combat is essentially a puzzle, so they literally replaced it with like the Bejeweled puzzle thing where you match orbs or jewels of the same color. I think each match was an attack, and I guess matching like 5 in a row would be a critical hit. We can replace our turn-based combat with some other kind of puzzle. A chess variant sounds good, like Tactics Arena Online. It would keep its turn-based elements we originally had in mind but really make the player think and use his imagination a lot more.

**Comment by Dloughrin** [comment]
Chess variant? So like a tactical turn based rpg, then. I actually really love those games. I've beaten every Fire Emblem game. This is something from the first english one, as an example. Is this what you meant?
https://www.youtube.com/watch?v=FgJzXnc6eK0

**Comment by magyk81** [comment]
Yes, I'd say that's pretty much exactly what I meant. And wow, I didn't know Japan was so inspired by Tolkien/King Arthur kind of stuff.

**Comment by Dloughrin** [comment]
Yeah, I've seen it a lot in the things I've seen from there.
I'd be up to make this the combat system, though. It's certainly more interesting. Good thing is that we can still use parts of the battle system we have.

**Comment by magyk81** [comment]
Yeah, I like how Tactics Arena, each combatant had its own initiative bar that worked the same we we have ours. It looked like Fire Emblem used that system of initiative too. In Tactics Arena, the mage would do an area damage of 5 squares (one middle, and the 4 adjacent), the witch would do a line of 5 squares, and the assassin's melee hit every adjacent square. So with the chess idea, the abilities we give the combatants can be a lot more unique.

**Comment by Dloughrin** [comment]
In Fire Emblem, it was strictly turn based. But I've played others that use initiative, too. 
I'll have to pretty much redo most of the stats though. I'll do that tomorrow. I'll also add a movement stat to each class.
